[package]
name = "ero-blockwheel-kv"
version = "0.1.4"
authors = ["Alexey Voznyuk <me@swizard.info>"]
description = "Key/value persistent store based on `ero-blockwheel` framework."
edition = "2018"

[dependencies]
ero = { git = "https://github.com/swizard0/ero.git", branch = "tokio_03" }
ero-blockwheel-fs = { git = "https://github.com/swizard0/ero-blockwheel-fs.git" }
alloc-pool = { git = "https://github.com/swizard0/alloc-pool.git" }

log = "^0.4"
serde = "^1.0"
futures = "^0.3"
bincode = "^1.2"
siphasher = "^0.3"
serde_derive = "^1.0"
