[package]
name = "ero-blockwheel-kv"
version = "0.1.0"
authors = ["Alexey Voznyuk <me@swizard.info>"]
description = "Key/value persistent store based on `ero-blockwheel`."
edition = "2018"

[dependencies]
ero = { git = "https://github.com/swizard0/ero.git", branch = "tokio_03" }
ero-blockwheel = { git = "https://github.com/swizard0/ero-blockwheel.git" }

log = "^0.4"
futures = "^0.3"
